Create-detrend-object
Ab2nour/stock-analysis pull request #13
Opened 2023-10-23 08:53 UTC by jExbrayat

Create detrend.py file defining the detrend class. 
Create a temporary demo notebook for easier visualisation of the detrend class' aim.

2023-10-23 11:29 UTC, Ab2nour requested changes

2023-10-23 11:29 UTC, Ab2nour commented on src/detrend.py
> +    def __init__(
init should be the first method of the class

2023-10-23 11:29 UTC, Ab2nour commented on src/detrend.py
> +    def fancy_plot(self, xticklabels=None) -> None:
add type hint for xticklabels

2023-10-23 11:32 UTC, jExbrayat commented
>  ok boomer

2023-10-23 11:32 UTC, jExbrayat commented
> init should be the first method of the class 

sorry boomer

2023-10-23 11:33 UTC, Ab2nour commented on src/detrend.py
> +    def fancy_plot(self, xticklabels=None) -> None:
ok :)

2023-10-23 11:48 UTC, Ab2nour requested changes

2023-10-23 11:48 UTC, Ab2nour commented on src/detrend.py
> +class detrend:
class names should be PascalCase

2023-10-23 11:58 UTC, Ab2nour approved these changes

2023-10-23 12:17 UTC, Ab2nour requested changes

2023-10-23 12:17 UTC, Ab2nour commented on src/detrend.py
> +        bsplines_factors: tuple = (10, 3),
type hint: set the size of the tuple
for example, tuple of 2 ints should be type hinted this way:
```py
bsplines_factors: tuple[int, int] = (10, 3),
```

2023-10-23 12:17 UTC, Ab2nour commented on src/detrend.py
> +        bsplines_factors: tuple = (10, 3),
type hint: set the size of the tuple
for example, tuple of 2 ints should be type hinted this way:
```py
bsplines_factors: tuple[int, int] = (10, 3),
```

2023-10-23 12:17 UTC, Ab2nour commented on src/detrend.py
> +        bsplines_factors: tuple = (10, 3),
type hint: set the size of the tuple
for example, tuple of 2 ints should be type hinted this way:
```py
bsplines_factors: tuple[int, int] = (10, 3),
```

2023-10-23 12:17 UTC, Ab2nour commented on src/detrend.py
> +        bsplines_factors: tuple = (10, 3),
type hint: set the size of the tuple
for example, tuple of 2 ints should be type hinted this way:
```py
bsplines_factors: tuple[int, int] = (10, 3),
```

2023-10-23 12:17 UTC, Ab2nour commented on src/detrend.py
> +    def fancy_plot(self, xticklabels: pd.core.indexes.base.Index | None = None) -> None:
add docstring

2023-10-23 12:17 UTC, Ab2nour commented on src/detrend.py
> +        x = np.arange(len(y))  # time dummy, x
maybe x and y should instead be named time_dummy and price?

2023-10-23 14:47 UTC, jExbrayat commented on src/detrend.py
> +        bsplines_factors: tuple = (10, 3),
done

2023-10-23 14:50 UTC, jExbrayat commented on src/detrend.py
> +        x = np.arange(len(y))  # time dummy, x
done

2023-10-23 14:56 UTC, jExbrayat commented on src/detrend.py
> +    def fancy_plot(self, xticklabels: pd.core.indexes.base.Index | None = None) -> None:
done

2023-10-29 13:11 UTC, Ab2nour commented
I merged [refactor/separate-methods-in-classes](https://github.com/Ab2nour/stock-analysis/pull/13/commits/b1bf723bc6c4f434ac4cc2e397243bb674538299) into this branch.

This branch also looks good to me, you can merge it into main, if you are finished.

2023-11-09 11:53 UTC, merged